function FIRButterworth

%
% M-File generated by MATLAB(R) 7.1 and the Signal Processing Toolbox 6.4.
%
% Generated on: 27-Apr-2006 15:48:54
%

% FIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in Hz.
Fs = 1;  % Sampling Frequency

N  = 80;     % Order
Fc = 0.1;  % Cutoff Frequency

%% Calculate the second-order sections coefficients to avoid round-off
%errors.
[b,a] = maxflat(N, 'sym', Fc/(Fs/2))

out = 1;
fprintf(out, 'double b[]={%.17g',b(1));
for j = 2: length(b)
    fprintf(out, ',%.17g', b(j));
end
fprintf(out, '};\n');
        
fprintf(out, 'double a[]={%.17g',a(1));
if (a > 1)
    for j = 1: length(a)
        fprintf(out, ',%.17g', a(j));
    end
end
fprintf(out, '};\n\n');
